spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 800       # 最大连接数（根据压测调整）
          max-idle: 400         # 最大空闲连接
          min-idle: 100         # 最小空闲连接
          max-wait: 50ms        # 连接等待超时时间
          time-between-eviction-runs: 30s # 空闲连接检测间隔
        shutdown-timeout: 5s
      timeout: 100ms            # 命令执行超时

  application:
    name: service-coupon
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: 192.168.244.140:8848
        file-extension: yaml
        shared-configs:
          - dataId: common-account.yaml
            refresh: true
  config:
    import:
      - optional:nacos:${spring.application.name}-dev.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:common-account.yaml
