---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/4/9 11:19
---
-- KEYS[1]: 优惠券信息key
-- KEYS[2...N]: 库存分段key (c:s:{couponId}:{segment})
-- KEYS[N+1]: 用户领取key (user:coupons:{userId}:{couponId})
-- KEYS[N+2]: 限领key (coupon:limit:{couponId})
-- ARGV[1]: 用户ID
-- ARGV[2]: 优惠券ID
-- ARGV[3]: 当前时间戳
-- ARGV[4]: 库存分段数量

-- 1. 检查优惠券基本信息
local coupon = redis.call('HGETALL', KEYS[1])
if not coupon or #coupon == 0 then
    return {-1, '优惠券不存在'}
end

-- 2. 检查状态
local status = redis.call('HGET', KEYS[1], 'status')
if status ~= '1' then
    return {-2, '优惠券不可用'}
end

-- 3. 检查时间有效性
local now = tonumber(ARGV[3])
local startTime = tonumber(redis.call('HGET', KEYS[1], 'startTime')) or 0
local expireTime = tonumber(redis.call('HGET', KEYS[1], 'expireTime')) or 0

if now < startTime then
    return {-3, '活动未开始'}
end

if now >= expireTime then
    return {-4, '活动已结束'}
end

-- 4. 检查限领
local limit = tonumber(redis.call('GET', KEYS[#KEYS])) or 0
if limit > 0 then
    local received = tonumber(redis.call('GET', KEYS[#KEYS-1])) or 0
    if received >= limit then
        return {-5, '已达到领取限制'}
    end
end

-- 5. 尝试从各库存分段扣减
local segmentCount = tonumber(ARGV[4])
local stockKeyIndex = 2 -- 库存key起始索引
local acquired = false

for i = 1, segmentCount do
    local stockKey = KEYS[stockKeyIndex]
    local stock = tonumber(redis.call('GET', stockKey)) or 0

    if stock > 0 then
        redis.call('DECR', stockKey)
        acquired = true
        break
    end

    stockKeyIndex = stockKeyIndex + 1
end

if not acquired then
    return {-6, '库存不足'}
end

-- 6. 记录用户领取
redis.call('INCR', KEYS[#KEYS-1])
redis.call('EXPIREAT', KEYS[#KEYS-1], expireTime)

return {1, '领取成功'}
