---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/6/18 11:00
---
-- 参数说明：
-- KEYS[1]: 库存key前缀 (如 "coupon:stock:{couponId}:")
-- ARGV[1]: 总段数
-- ARGV[2]: 基础TTL秒数
-- ARGV[3]: 最后一段库存数
-- ARGV[4]: 随机数种子（可选）

-- 设置随机种子（如果传入种子）
--if ARGV[4] ~= nil then
--    math.randomseed(tonumber(ARGV[4]))
--end
--
--for i = 0, tonumber(ARGV[1]) - 1 do
--    local stock = (i == tonumber(ARGV[1]) - 1) and tonumber(ARGV[3]) or 100
--    -- 在基础TTL上增加随机偏移（10-300秒）
--    local random_ttl = tonumber(ARGV[2]) + math.random(10, 300)
--    redis.call("SET", KEYS[1] .. i, stock, "EX", random_ttl)
--end
--return 1


-- KEYS[1]: 库存Hash的key (如 "coupon:stock:{couponId}")
-- ARGV[1]: 总段数
-- ARGV[2]: 基础TTL秒数
-- ARGV[3]: 最后一段库存数
-- ARGV[4]: 随机种子（可选）

if ARGV[4] ~= nil then
    math.randomseed(tonumber(ARGV[4]))
end

-- 1. 删除旧数据（避免重复预热）
redis.call("DEL", KEYS[1])

-- 2. 写入分段库存到Hash
local segments = tonumber(ARGV[1])
for i = 0, segments - 1 do
    local stock = (i == segments - 1) and tonumber(ARGV[3]) or 100
    redis.call("HSET", KEYS[1], "seg_" .. i, stock)
end

-- 3. 设置TTL（整个Hash统一过期）
local random_ttl = tonumber(ARGV[2]) + (ARGV[4] and math.random(10, 300) or 0)
redis.call("EXPIRE", KEYS[1], random_ttl)

return 1
