---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/3/29 21:55
---
local orderId = ARGV[1]
local driverId = ARGV[2]
local customerId = ARGV[3]
local key = "orders:dc:" .. orderId
redis.call('HSET', key, "driverId", driverId, "customerId", customerId)
redis.call('EXPIRE', key, ARGV[4])
return 1
