---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/4/6 22:53
---
local ORDER_ACCEPT_MARK = "o:a:m:" .. ARGV[1]
-- 符合订单条件的司机
redis.call('SADD', ORDER_ACCEPT_MARK, ARGV[2])
-- 过期时间
redis.call('EXPIRE', ORDER_ACCEPT_MARK, ARGV[3])
