spring:
  application:
    name: web-driver
  cloud:
    openfeign:
      client:
        config:
          default:
            #连接超时时间
            connectTimeout: 100000
            #读取超时时间
            readTimeout: 100000
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: 192.168.244.140:8848
        file-extension: yaml
        shared-configs:
          - dataId: common-account.yaml
            refresh: true
  config:
    import:
      - optional:nacos:${spring.application.name}-dev.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:common-account.yaml
