spring:
  application:
    name: web-customer
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: 192.168.244.140:8848
        file-extension: yaml
        shared-configs:
          - dataId: common-account.yaml
            refresh: true


  config:
    import:
      - optional:nacos:${spring.application.name}-dev.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:common-account.yaml
seata:
  # 当前应用的事务组名称（需唯一）
  tx-service-group: tingshu-tx-group
  service:
    # 事务组到集群的映射
    vgroup-mapping:
      tingshu-tx-group: default  # 表示tingshu-tx-group事务组属于default集群
    # 集群对应的TC服务器地址
    grouplist:
      default: 192.168.244.140:8091    # default集群的Transaction Coordinator地址
