---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/3/27 19:07
---
local orderId = ARGV[1]
local driverId = ARGV[2]
local driver_order_id_zset = "driver:zet:orders:" .. driverId
local driver_order_info_hash = "driver:hash:orders:" .. driverId
redis.call("ZREM", driver_order_id_zset, orderId)
redis.call("HDEL", driver_order_info_hash, orderId)
return 1

--local driver_order_id_zset = "driver:zet:orders:" .. driverId
--local driver_order_info_hash = "driver:hash:orders:" .. driverId
--redis.call("ZREM", driver_order_id_zset, orderId)
--redis.call("HDEL", driver_order_info_hash, orderId)
--return 1
