---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/3/27 20:37
---
local driverId = ARGV[1]
local driver_order_id_zset = "driver:zet:orders:" .. driverId
local driver_order_info_hash = "driver:hash:orders:" .. driverId
redis.call('unlink', driver_order_id_zset)
redis.call('unlink', driver_order_info_hash)
return 1
