---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/3/27 11:34
---
-- 将符合条件的订单插入到司机接单池
local orderId = ARGV[1]
local driverId = ARGV[2]
local driver_order_id_zset = "driver:zet:orders:" .. driverId
local driver_order_info_hash = "driver:hash:orders:" .. driverId
local ORDER_ACCEPT_MARK = "o:a:m:" .. orderId

-- 防止重复推送
if redis.call('SISMEMBER', ORDER_ACCEPT_MARK, driverId) == 1 then
    return 0
end

-- 符合订单条件的司机
redis.call('SADD', ORDER_ACCEPT_MARK, driverId)
redis.call("ZADD", driver_order_id_zset, tonumber(ARGV[3]), orderId)
redis.call("HSET", driver_order_info_hash, orderId, ARGV[4])
redis.call('EXPIRE', driver_order_id_zset, ARGV[5])
redis.call('EXPIRE', driver_order_info_hash, ARGV[5])
return 1
