---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2025/3/27 11:34
---
-- KEYS[1]: 有序集合的键名（如司机订单池的key）
-- ARGV[1]: 订单数据的JSON字符串（newOrderDataVo序列化结果）
-- ARGV[2]: 过期时间（单位：秒）

-- 添加订单到ZSET（分数为当前时间戳）
--redis.call('ZADD', KEYS[1], tonumber(ARGV[1]), ARGV[2])
--
---- 设置过期时间（15分钟 = 900秒）
--redis.call('EXPIRE', KEYS[1], ARGV[3])
--
--return 1  -- 返回成功标识

-- Lua脚本保证原子性：抢单+状态校验+删除ZSET成员
--local orderId = ARGV[1]
--local driverId = ARGV[2]
--local orderKey = "order:details:" .. orderId
--local driverKey = "driver:orders:" .. driverId
--
---- 校验订单状态是否为pending
--local status = redis.call("HGET", orderKey, "status")
--if status ~= "pending" then
--    return 0 -- 订单已被抢或取消
--end
--
---- 更新订单状态为accepted
--redis.call("HSET", orderKey, "status", "accepted")
--redis.call("HSET", orderKey, "driverId", driverId)
--
---- 从司机接单池移除
--redis.call("ZREM", driverKey, orderId)
--return 1 -- 抢单成功
-- 将符合条件的订单插入到司机接单池
local orderId = ARGV[1]
local driverId = ARGV[2]
local driver_order_id_zset = "driver:zet:orders:" .. driverId
local driver_order_info_hash = "driver:hash:orders:" .. driverId
local ORDER_ACCEPT_MARK = "o:a:m:" .. orderId
-- 符合订单条件的司机
redis.call('SADD', ORDER_ACCEPT_MARK, driverId)
redis.call("ZADD", driver_order_id_zset, tonumber(ARGV[3]), orderId)
redis.call("HSET", driver_order_info_hash, orderId, ARGV[4])
redis.call('EXPIRE', driver_order_id_zset, ARGV[5])
redis.call('EXPIRE', driver_order_info_hash, ARGV[5])
return 1
